flowchart TD

A[User Guess]

B[Streamlit UI]

C[Agent]

D[Analysis]

E[Planning]

F[Hint Generator]

G[Validator]

H[Logger]

I[Display Result]


A --> B
B --> C
C --> D
D --> E
E --> F
F --> G
G --> H
H --> I